default:
  image: python:3.9

stages:
  - lint
  - test

variables:
  POETRY_VERSION: 1.4.2
before_script:
  - curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION
  - export PATH="/root/.local/bin:$PATH"
  - poetry config -- http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
  - poetry install --sync

lint-python:
  stage: lint
  needs: [ ]
  script:
    - poetry run bin/lint.sh --check


test-python:
  stage: test
  needs: [ ]
  script:
    - poetry run pytest

test-catwalk:
  stage: test
  needs: [ ]
  script:
    - timeout 5 poetry run server src/cube &
    - curl -sS --retry-connrefused --retry 3 --fail http://localhost:3000/docs
