default:
  image: python:3.11

stages:
  - lint
  - test

# See https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

variables:
  POETRY_VERSION: 1.8.3
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  NIX_IMAGE: "registry.gitlab.com/generative/infra/base-images/nixos:2024.06.10.16.03"  # 24.05
  CACHIX_AUTH_TOKEN: $CACHIX_AUTH_TOKEN_RW


lint-in-nix:
  stage: test
  needs: [ ]
  image: $NIX_IMAGE
  script:
    # Basic hygiene
    - nix flake check --keep-going
    - poetry install
    - poetry check
    - poetry run mypy


test-python:
  stage: test
  needs: [ ]
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION
    - export PATH="/root/.local/bin:$PATH"
    - poetry config -- http-basic.generative-gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry install --sync
  script:
    - poetry run pytest


test-in-nix-shell:
  stage: test
  needs: [ ]
  image: $NIX_IMAGE
  tags:
    - saas-linux-medium-amd64
  script:
    # Basic hygiene
    - nix flake check
    # Pull dependencies etc
    - poetry install
    # Run all the tests
    - poetry run pytest
    - timeout 7 poetry run server src/cube &
    - curl -sS --retry-connrefused --retry 5 --retry-delay 1 --fail http://localhost:3000/docs
