default:
  image: python:3.9

stages:
  - lint
  - test

# See https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

variables:
  POETRY_VERSION: 1.4.2
before_script:
  - curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION
    # libgl1 is required for CADQuery
  - apt-get update -q
  - apt-get install -qy libgl1
  - export PATH="/root/.local/bin:$PATH"
  - poetry config -- http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
  - poetry install --sync

lint-python:
  stage: lint
  needs: [ ]
  script:
    - poetry run bin/lint.sh --check


test-python:
  stage: test
  needs: [ ]
  script:
    - poetry run pytest

test-catwalk:
  stage: test
  needs: [ ]
  script:
    - timeout 7 poetry run server src/cube &
    - curl -sS --retry-connrefused --retry 5 --retry-delay 1 --fail http://localhost:3000/docs
