default:
  image: python:3.8-slim-buster

stages:
  - lint
  - test

variables:
  POETRY_VERSION: 1.2.2
  DESIGN_SPEC: designs/explore_cube.yaml

before_script:
  - pip install -qq "poetry==$POETRY_VERSION"
  # Beware the tokens: https://github.com/python-poetry/poetry/issues/2889
  - poetry config -- http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
  - poetry install --sync
  - poetry debug info

lint-python:
  stage: lint
  needs: [ ]
  script:
    - poetry run bin/lint.sh --check


test-python:
  stage: test
  needs: [ ]
  script:
    - poetry run pytest

test-design-file-runs:
  stage: test
  needs: [ ]
  script:
    - poetry run explorer run $DESIGN_SPEC

test-design-files-compile:
  stage: test
  needs: [ ]
  script:
    - for f in designs/*.yaml; do poetry run explorer compile $f; done
