default:
  image: python:3.13

stages:
  - lint
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  POETRY_VERSION: 1.8.3
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  NIX_IMAGE: "registry.gitlab.com/generative/infra/nixos-ci:2024.10.30.17.38"  # 24.05
  CACHIX_AUTH_TOKEN: $CACHIX_AUTH_TOKEN_RW


lint-in-nix:
  stage: test
  needs: [ ]
  image: $NIX_IMAGE
  script:
    - nix flake check --keep-going
    - poetry install
    - poetry check
    - poetry run mypy

test-pythons:
  parallel:
    matrix:
      - PYTHON_IMAGE_VERSION:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
  image: "python:$PYTHON_IMAGE_VERSION"
  needs: [ ]
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION
    - export PATH="/root/.local/bin:$PATH"
    - poetry config -- http-basic.generative-gitlab gitlab-ci-token "$CI_JOB_TOKEN"
    - poetry install --sync
  script:
    - poetry check
    - poetry run pytest


test-in-nix-shell:
  stage: test
  needs: [ ]
  image: $NIX_IMAGE
  script:
    # Basic hygiene
    - nix flake check
    # Pull dependencies etc
    - poetry install
    # Run all the tests
    - poetry run pytest
    - timeout 7 poetry run server fabricfunctions &
    - curl -sS --retry-connrefused --retry 5 --retry-delay 1 --fail http://localhost:3000/docs
