# Use default, but disable a few things for sanity
default: true
MD013:
  code_blocks: false
  line_length: 110
MD003:
  style: setext_with_atx
MD022:
  lines_below: 0
# It's fine to have two spaces sometimes
MD012: false
# no-duplicate-heading/no-duplicate-header : breaks our changelog badly
MD024: false
# Code blocks don't really need blank lines
MD031: false
# Bullets with no space are probably just fine
MD032: false
